### ISSUE TITLE
LINKVIEW2 支持 MUMMER吗

### ISSUE THREAD

**Issue by Johnsonzcode** [YangJianshun/LINKVIEW2#2]
感谢作者的开源！
如题

**Comment by YangJianshun** [comment]
这片文档里面列出了 LINKVIEW2 支持的 alignments 文件格式：https://github.com/YangJianshun/LINKVIEW2/wiki/LINKVIEW2-%E5%8F%82%E6%95%B0%E6%96%87%E6%A1%A3

**Comment by Johnsonzcode** [comment]
感谢！！！

**Comment by Johnsonzcode** [comment]
你好，请问LINKVIEW2可以吧link绘成有颜色的吗，可以增添相关参数吗

**Comment by Johnsonzcode** [comment]
@YangJianshun

**Comment by Johnsonzcode** [comment]
能把共线性的表示方式表示为线条连接而不是块状吗

**Comment by YangJianshun** [comment]
> 能把共线性的表示方式表示为线条连接而不是块状吗

不能。块变得很细的时候就是线条。可以通过自定义 alignments 文件，自己构造很细的块。

**Comment by Johnsonzcode** [comment]
配色可以用配色的代码而不仅是英文吗

**Comment by YangJianshun** [comment]
> 配色可以用配色的代码而不仅是英文吗
svg 支持的颜色都可以。你可以在 LINKVIEW-GUI 中试一试

**Comment by YangJianshun** [comment]
问题已经解决
