### ISSUE TITLE
dpi

### ISSUE THREAD

**Issue by Johnsonzcode** [YangJianshun/LINKVIEW2#3]
请问：
LINKVIEW2自动输出的svg怎么转换成高dpi的png，或者默认的dpi是多少？

**Comment by comery** [comment]
自己用AI，Inkscape或者其他软件打开，然后导出到图片(png)就可以选择dpi，一般文章发表300dpi就差不多了。

**Comment by YangJianshun** [comment]
> 自己用AI，Inkscape或者其他软件打开，然后导出到图片(png)就可以选择dpi，一般文章发表300dpi就差不多了。

是的，实际上为了实现 svg 渲染成 png，引入了一个库，导致安装 LINKVIEW 的时候可能比较慢，甚至安装失败。都想移除这个依赖了。只提供生成 svg 的能力。

**Comment by Johnsonzcode** [comment]
最后用了python包cairosvg，谢谢！
