### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by mengxiaoqian** [YangJianshun/LINKVIEW2#4]
感谢作者大大的开源精神！本人在使用中也有很不错的体验！如果能在后续版本中添加一些功能就更完美了。。。
1. 根据匹配赋予的颜色分配图例。 根据示例我构建了alignment文件，并在每一行后对正向匹配赋予灰色，而反向匹配赋予红色，我想如果能根据这些颜色分配图例，就能让阅读者清楚的知道线条的意思。
2. 由常规方法blast，minima2，nucmer自动生成的文件也能根据区段匹配的特性分配固定的颜色，不知道是否更加便捷？
3.指定的高亮区域能否展示文本信息？也即在hightlight文件后添加一列文本展示信息！

上述建议只是本人的一点小小看法，相比大多数可视化工具来说，该软件已经做的非常优异！祝作者再创佳绩！

**Comment by YangJianshun** [comment]
> 

1. 增加图例功能
2. 不明白你的意思，能否举例说明
3. 增加注释功能（可以考虑对 highlight、gene 等标注一些文本）

你的建议会在后续版本考虑，目前可以考虑用 ppt 自己画一下。

**Comment by mengxiaoqian** [comment]
感谢作者大大的回复！
第二点的意思是 ”根据blast等比对软件的结果自动判断正反向，并赋予颜色。 这样可以指示染色体是否为倒位或者反转等”

**Comment by YangJianshun** [comment]
> 

你好，图例功能暂时不考虑开发。本工具的定位是：（1）快速绘制共线性图，方便日常科研工作。（2）帮助绘制论文级别插图。
图例一般是第（2）种情况，本工具出的图，还需要经过精心处理才能作为论文级别插图。通过命令行参数来控制图例不是很明智的选择，毕竟一般图例都是比较个性化的。 

后续会考虑开发更具有交互性的 GUI 程序，会考虑图例的绘制。
